import base64
import re
import requests as http_requests

def create_github_pr(
    github_token: str,
    repo_url: str,
    base_branch: str,
    branch_name: str,
    patched_file: str,
    patched_code: str,
    scan_id: str | int,
    gate: str,
    gate_rationale: str,
    explanation: str,
    critical_count: int = 0,
    high_count: int = 0,
    tag_user: str = None,
    direct: bool = False
):
    """
    Creates a branch, pushes the patched_code to patched_file, and opens a PR.
    If direct=True, pushes directly to base_branch.
    """
    repo_url = repo_url.rstrip("/")
    parts = repo_url.replace("https://github.com/", "").split("/")
    if len(parts) < 2:
        raise ValueError("Cannot parse owner/repo from scan URL")
    owner, repo = parts[0], parts[1]

    patched_file = (patched_file or "resiliocheck_patch.txt").lstrip("/")
    if not re.match(r"^[A-Za-z0-9._\-/]+$", patched_file) or ".." in patched_file.split("/"):
        raise ValueError("Stored patch filename is invalid")

    headers = {
        "Authorization": f"Bearer {github_token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    
    # 1. Get default branch SHA
    ref_resp = http_requests.get(
        f"https://api.github.com/repos/{owner}/{repo}/git/ref/heads/{base_branch}",
        headers=headers, timeout=15,
    )
    if ref_resp.status_code != 200:
        raise ValueError(f"GitHub ref lookup failed ({ref_resp.status_code}): {ref_resp.text[:300]}")
    base_sha = ref_resp.json()["object"]["sha"]

    # 2. Create fix branch
    if not direct:
        create_branch = http_requests.post(
            f"https://api.github.com/repos/{owner}/{repo}/git/refs",
            headers=headers,
            json={"ref": f"refs/heads/{branch_name}", "sha": base_sha},
            timeout=15,
        )
        if create_branch.status_code not in (201, 422):
            raise ValueError(f"Branch creation failed ({create_branch.status_code}): {create_branch.text[:300]}")

    # 3. Get current file SHA
    target_branch = base_branch if direct else branch_name
    file_resp = http_requests.get(
        f"https://api.github.com/repos/{owner}/{repo}/contents/{patched_file}",
        headers=headers,
        params={"ref": target_branch},
        timeout=15,
    )
    file_sha = file_resp.json().get("sha") if file_resp.status_code == 200 else None

    # 4. Push patched file
    content_b64 = base64.b64encode(patched_code.encode()).decode()
    update_payload = {
        "message": f"fix(resiliocheck): AI-generated security patch for scan #{scan_id}",
        "content": content_b64,
        "branch": target_branch,
    }
    if file_sha:
        update_payload["sha"] = file_sha

    push_resp = http_requests.put(
        f"https://api.github.com/repos/{owner}/{repo}/contents/{patched_file}",
        headers=headers,
        json=update_payload,
        timeout=15,
    )
    if push_resp.status_code not in (200, 201):
        raise ValueError(f"File push failed ({push_resp.status_code}): {push_resp.text[:300]}")

    # 5. Open Pull Request
    if not direct:
        body = (
            f"**Automated security patch generated by ResilioCheck AI.**\n\n"
            f"**Scanned Repository:** {repo_url}\n"
            f"**Branch:** `{base_branch}`\n"
            f"**Gate Verdict:** `{gate}`\n"
            f"**Findings:** {critical_count} critical, {high_count} high\n\n"
            f"### Rationale\n{gate_rationale}\n\n"
            f"### AI Explanation\n{explanation}\n"
        )
        if tag_user:
            body += f"\n\ncc @{tag_user}"

        pr_resp = http_requests.post(
            f"https://api.github.com/repos/{owner}/{repo}/pulls",
            headers=headers,
            json={
                "title": f"[ResilioCheck AI] Security Fix — Scan #{scan_id}",
                "body": body,
                "head": branch_name,
                "base": base_branch,
            },
            timeout=15,
        )
        if pr_resp.status_code not in (200, 201):
            raise ValueError(f"PR creation failed ({pr_resp.status_code}): {pr_resp.text[:300]}")

        pr_url = pr_resp.json().get("html_url", "")
    else:
        pr_url = f"{repo_url}/commit/{push_resp.json()['commit']['sha']}"

    return pr_url, target_branch
